from tkinter import*
def add():
    res=int(e1.get())+int(e2.get())
    myText.set(res)
top=Tk()
top.geometry("500x400")
myText=StringVar()
labelframe1=LabelFrame(top,text="Summation")
labelframe1.pack(fill="both",expand="yes")
toplabel=Label(labelframe1,text="enter first number")
toplabel.pack()
e1=Entry(labelframe1)
e1.pack()
toplabel1=Label(labelframe1,text="Enter second number")
toplabel1.pack()
e2=Entry(labelframe1)
e2.pack()
result=Label(labelframe1,text="",textvariable=myText)
result.pack()
b=Button(labelframe1,text="result",command=add)
b.pack()
def sub():
    res=int(e3.get())-int(e4.get())
    myText1.set(res)
myText1=StringVar()
labelframe2=LabelFrame(top,text="Subtraction")
labelframe2.pack(fill="both",expand="yes")
bottomlabel=Label(labelframe2,text="Enter first number")
bottomlabel.pack()
e3=Entry(labelframe2)
e3.pack()
bottomlabel1=Label(labelframe2,text="Enter second number")
bottomlabel1.pack()
e4=Entry(labelframe2)
e4.pack()
result=Label(labelframe2,text="",textvariable=myText1)
result.pack()
b1=Button(labelframe2,text="result",command=sub)
b1.pack()
def mul():
    res=int(e5.get())*int(e6.get())
    myText2.set(res)
myText2=StringVar()
labelframe3=LabelFrame(top,text="Multiplication")
labelframe3.pack(fill="both",expand="yes")
bottomlabel2=Label(labelframe3,text="Enter first number")
bottomlabel2.pack()
e5=Entry(labelframe3)
e5.pack()
bottomlabel3=Label(labelframe3,text="Enter second number")
bottomlabel3.pack()
e6=Entry(labelframe3)
e6.pack()
result=Label(labelframe3,text="",textvariable=myText2)
result.pack()
b2=Button(labelframe3,text="result",command=mul)
b2.pack()
def div():
    res=int(e7.get())/int(e8.get())
    myText3.set(res)
myText3=StringVar()
labelframe4=LabelFrame(top,text="Division")
labelframe4.pack(fill="both",expand="yes")
bottomlabel4=Label(labelframe4,text="Enter first number")
bottomlabel4.pack()
e7=Entry(labelframe4)
e7.pack()
bottomlabel5=Label(labelframe4,text="Enter second number")
bottomlabel5.pack()
e8=Entry(labelframe4)
e8.pack()
result=Label(labelframe4,text="",textvariable=myText3)
result.pack()
b3=Button(labelframe4,text="result",command=div)
b3.pack()
top.mainloop()

