from tkinter import*
def add():
    res=int(e1.get())+int(e2.get())
    myText.set(res)
    top=Tk()
    top.geometry("500x400")
    myText=String Var()
    label frame1=Label Frame(top,text="summation")
    label frame1.pack(fill="both",expand="yes")
    top label=Label(top,text="enter the first number")
    top label.pack()
    e1=Entry(label frame1)
    e1.pack()
    top label1=Label(top,text="enter the second number")
    top label1.pack()
    e2=Entry(label frame1)
    e2.pack()
    result=Label(top,text="",textvariable=my Text)
    b1=Button(label frame1,text="result",command="add")
    b1.pack()
    top.mainloop()